<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RoleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
           'role_title' => ['required', 'string', 'unique:gt_roles,role,'.$this->id],
           'permissions.branches.create_branch' => ['required', 'boolean'],
           'permissions.branches.view_branches' => ['required', 'boolean'],
           'permissions.branches.update_branch' => ['required', 'boolean'],
           'permissions.branches.delete_branch' => ['required', 'boolean'],
           'permissions.roles.create_role' => ['required', 'boolean'],
           'permissions.roles.view_roles' => ['required', 'boolean'],
           'permissions.roles.view_permissions' => ['required', 'boolean'],
           'permissions.roles.update_role' => ['required', 'boolean'],
           'permissions.roles.delete_role' => ['required', 'boolean'],
           'permissions.users.create_users' => ['required', 'boolean'],
           'permissions.users.assign_user_role' => ['required', 'boolean'],
           'permissions.users.assign_user_status' => ['required', 'boolean'],
           'permissions.users.view_users' => ['required', 'boolean'],
           'permissions.users.view_roles' => ['required', 'boolean'],
           'permissions.users.view_status' => ['required', 'boolean'],
           'permissions.users.view_own_users' => ['required', 'boolean'],
           'permissions.users.view_self' => ['required', 'boolean'],
           'permissions.users.view_self_role' => ['required', 'boolean'],
           'permissions.users.view_self_status' => ['required', 'boolean'],
           'permissions.users.update_users' => ['required', 'boolean'],
           'permissions.users.update_all_roles' => ['required', 'boolean'],
           'permissions.users.update_all_status' => ['required', 'boolean'],
           'permissions.users.update_own_users' => ['required', 'boolean'],
           'permissions.users.update_own_role' => ['required', 'boolean'],
           'permissions.users.update_own_status' => ['required', 'boolean'],
           'permissions.users.update_self' => ['required', 'boolean'],
           'permissions.users.update_self_role' => ['required', 'boolean'],
           'permissions.users.update_self_status' => ['required', 'boolean'],
           'permissions.users.delete_users' => ['required', 'boolean'],
           'permissions.users.delete_own_users' => ['required', 'boolean'],
           'permissions.users.delete_self' => ['required', 'boolean'],
           'permissions.pendingusers.assign_activate' => ['required', 'boolean'],
           'permissions.pendingusers.view_pending_users' => ['required', 'boolean'],
           'permissions.pendingusers.delete_pending_users' => ['required', 'boolean'],
           'permissions.waitlist.move_to_hold' => ['required', 'boolean'],
           'permissions.waitlist.move_to_blacklist' => ['required', 'boolean'],
           'permissions.waitlist.move_to_refund' => ['required', 'boolean'],
           'permissions.waitlist.create_trainees' => ['required', 'boolean'],
           'permissions.waitlist.assign_class' => ['required', 'boolean'],
           'permissions.waitlist.assign_trainer' => ['required', 'boolean'],
           'permissions.waitlist.assign_level' => ['required', 'boolean'],
           'permissions.waitlist.view_trainees' => ['required', 'boolean'],
           'permissions.waitlist.view_trainers' => ['required', 'boolean'],
           'permissions.waitlist.view_levels' => ['required', 'boolean'],
           'permissions.waitlist.view_own_trainees' => ['required', 'boolean'],
           'permissions.waitlist.view_own_trainers' => ['required', 'boolean'],
           'permissions.waitlist.view_own_levels' => ['required', 'boolean'],
           'permissions.waitlist.update_trainees' => ['required', 'boolean'],
           'permissions.waitlist.update_all_trainers' => ['required', 'boolean'],
           'permissions.waitlist.update_all_levels' => ['required', 'boolean'],
           'permissions.waitlist.update_own_trainees' => ['required', 'boolean'],
           'permissions.waitlist.update_own_trainers' => ['required', 'boolean'],
           'permissions.waitlist.update_own_levels' => ['required', 'boolean'],
           'permissions.waitlist.delete_trainees' => ['required', 'boolean'],
           'permissions.waitlist.delete_own_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.create_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.assign_follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.assign_trainer' => ['required', 'boolean'],
           'permissions.pendinglist.assign_level' => ['required', 'boolean'],
           'permissions.pendinglist.view_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.view_follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.view_trainers' => ['required', 'boolean'],
           'permissions.pendinglist.view_levels' => ['required', 'boolean'],
           'permissions.pendinglist.view_own_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.view_own_follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.view_trainers' => ['required', 'boolean'],
           'permissions.pendinglist.view_levels' => ['required', 'boolean'],
           'permissions.pendinglist.update_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.update_all_trainers' => ['required', 'boolean'],
           'permissions.pendinglist.update_all_levels' => ['required', 'boolean'],
           'permissions.pendinglist.update_own_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.update_own_trainers' => ['required', 'boolean'],
           'permissions.pendinglist.update_own_levels' => ['required', 'boolean'],
           'permissions.pendinglist.delete_trainees' => ['required', 'boolean'],
           'permissions.pendinglist.delete_own_trainees' => ['required', 'boolean'],
           'permissions.holdlist.assign_trainer' => ['required', 'boolean'],
           'permissions.holdlist.assign_level' => ['required', 'boolean'],
           'permissions.holdlist.view_trainees' => ['required', 'boolean'],
           'permissions.holdlist.view_trainers' => ['required', 'boolean'],
           'permissions.holdlist.view_levels' => ['required', 'boolean'],
           'permissions.holdlist.view_own_trainees' => ['required', 'boolean'],
           'permissions.holdlist.view_own_trainers' => ['required', 'boolean'],
           'permissions.holdlist.view_own_levels' => ['required', 'boolean'],
           'permissions.holdlist.update_trainees' => ['required', 'boolean'],
           'permissions.holdlist.update_all_trainers' => ['required', 'boolean'],
           'permissions.holdlist.update_all_levels' => ['required', 'boolean'],
           'permissions.holdlist.update_own_trainees' => ['required', 'boolean'],
           'permissions.holdlist.update_own_trainers' => ['required', 'boolean'],
           'permissions.holdlist.update_own_levels' => ['required', 'boolean'],
           'permissions.holdlist.delete_trainees' => ['required', 'boolean'],
           'permissions.holdlist.delete_own_trainees' => ['required', 'boolean'],
           'permissions.refundlist.assign_trainer' => ['required', 'boolean'],
           'permissions.refundlist.assign_level' => ['required', 'boolean'],
           'permissions.refundlist.view_trainees' => ['required', 'boolean'],
           'permissions.refundlist.view_trainers' => ['required', 'boolean'],
           'permissions.refundlist.view_levels' => ['required', 'boolean'],
           'permissions.refundlist.view_own_trainees' => ['required', 'boolean'],
           'permissions.refundlist.view_own_trainers' => ['required', 'boolean'],
           'permissions.refundlist.view_own_levels' => ['required', 'boolean'],
           'permissions.refundlist.update_trainees' => ['required', 'boolean'],
           'permissions.refundlist.update_all_trainers' => ['required', 'boolean'],
           'permissions.refundlist.update_all_levels' => ['required', 'boolean'],
           'permissions.refundlist.update_own_trainees' => ['required', 'boolean'],
           'permissions.refundlist.update_own_trainers' => ['required', 'boolean'],
           'permissions.refundlist.update_own_levels' => ['required', 'boolean'],
           'permissions.refundlist.delete_trainees' => ['required', 'boolean'],
           'permissions.refundlist.delete_own_trainees' => ['required', 'boolean'],
           'permissions.blacklist.assign_trainer' => ['required', 'boolean'],
           'permissions.blacklist.assign_level' => ['required', 'boolean'],
           'permissions.blacklist.view_trainees' => ['required', 'boolean'],
           'permissions.blacklist.view_trainers' => ['required', 'boolean'],
           'permissions.blacklist.view_levels' => ['required', 'boolean'],
           'permissions.blacklist.view_own_trainees' => ['required', 'boolean'],
           'permissions.blacklist.view_own_trainers' => ['required', 'boolean'],
           'permissions.blacklist.view_own_levels' => ['required', 'boolean'],
           'permissions.blacklist.update_trainees' => ['required', 'boolean'],
           'permissions.blacklist.update_all_trainers' => ['required', 'boolean'],
           'permissions.blacklist.update_all_levels' => ['required', 'boolean'],
           'permissions.blacklist.update_own_trainees' => ['required', 'boolean'],
           'permissions.blacklist.update_own_trainers' => ['required', 'boolean'],
           'permissions.blacklist.update_own_levels' => ['required', 'boolean'],
           'permissions.blacklist.delete_trainees' => ['required', 'boolean'],
           'permissions.blacklist.delete_own_trainees' => ['required', 'boolean'],
           'permissions.trainees.*' => ['required', 'boolean'],
           'permissions.batches.*' => ['required', 'boolean'],
        ];
    }
}