<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RoleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
           'role_title' => ['required', 'string', 'unique:gt_roles,role,'.$this->id],
           'permissions.branches.create-branch' => ['required', 'boolean'],
           'permissions.branches.view-branches' => ['required', 'boolean'],
           'permissions.branches.update-branch' => ['required', 'boolean'],
           'permissions.branches.delete-branch' => ['required', 'boolean'],
           'permissions.roles.create-role' => ['required', 'boolean'],
           'permissions.roles.view-roles' => ['required', 'boolean'],
           'permissions.roles.view-permissions' => ['required', 'boolean'],
           'permissions.roles.update-role' => ['required', 'boolean'],
           'permissions.roles.delete-role' => ['required', 'boolean'],
           'permissions.users.create-users' => ['required', 'boolean'],
           'permissions.users.assign-user-role' => ['required', 'boolean'],
           'permissions.users.assign-user-status' => ['required', 'boolean'],
           'permissions.users.view-users' => ['required', 'boolean'],
           'permissions.users.view-roles' => ['required', 'boolean'],
           'permissions.users.view-status' => ['required', 'boolean'],
           'permissions.users.view-own-users' => ['required', 'boolean'],
           'permissions.users.view-self' => ['required', 'boolean'],
           'permissions.users.view-self-role' => ['required', 'boolean'],
           'permissions.users.view-self-status' => ['required', 'boolean'],
           'permissions.users.update-users' => ['required', 'boolean'],
           'permissions.users.update-all-roles' => ['required', 'boolean'],
           'permissions.users.update-all-status' => ['required', 'boolean'],
           'permissions.users.update-own-users' => ['required', 'boolean'],
           'permissions.users.update-own-role' => ['required', 'boolean'],
           'permissions.users.update-own-status' => ['required', 'boolean'],
           'permissions.users.update-self' => ['required', 'boolean'],
           'permissions.users.update-self-role' => ['required', 'boolean'],
           'permissions.users.update-self-status' => ['required', 'boolean'],
           'permissions.users.delete-users' => ['required', 'boolean'],
           'permissions.users.delete-own-users' => ['required', 'boolean'],
           'permissions.users.delete-self' => ['required', 'boolean'],
           'permissions.pendingusers.assign-activate' => ['required', 'boolean'],
           'permissions.pendingusers.view-pending-users' => ['required', 'boolean'],
           'permissions.pendingusers.delete-pending-users' => ['required', 'boolean'],
           'permissions.waitlist.create-trainees' => ['required', 'boolean'],
           'permissions.waitlist.assign-class' => ['required', 'boolean'],
           'permissions.waitlist.assign-trainer' => ['required', 'boolean'],
           'permissions.waitlist.assign-level' => ['required', 'boolean'],
           'permissions.waitlist.view-trainees' => ['required', 'boolean'],
           'permissions.waitlist.view-trainers' => ['required', 'boolean'],
           'permissions.waitlist.view-levels' => ['required', 'boolean'],
           'permissions.waitlist.view-own-trainees' => ['required', 'boolean'],
           'permissions.waitlist.view-own-trainers' => ['required', 'boolean'],
           'permissions.waitlist.view-own-levels' => ['required', 'boolean'],
           'permissions.waitlist.update-trainees' => ['required', 'boolean'],
           'permissions.waitlist.update-all-trainers' => ['required', 'boolean'],
           'permissions.waitlist.update-all-levels' => ['required', 'boolean'],
           'permissions.waitlist.update-own-trainees' => ['required', 'boolean'],
           'permissions.waitlist.update-own-trainers' => ['required', 'boolean'],
           'permissions.waitlist.update-own-levels' => ['required', 'boolean'],
           'permissions.waitlist.delete-trainees' => ['required', 'boolean'],
           'permissions.waitlist.delete-own-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.create-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.assign-follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.assign-trainer' => ['required', 'boolean'],
           'permissions.pendinglist.assign-level' => ['required', 'boolean'],
           'permissions.pendinglist.view-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.view-follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.view-trainers' => ['required', 'boolean'],
           'permissions.pendinglist.view-levels' => ['required', 'boolean'],
           'permissions.pendinglist.view-own-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.view-own-follow_up' => ['required', 'boolean'],
           'permissions.pendinglist.view-trainers' => ['required', 'boolean'],
           'permissions.pendinglist.view-levels' => ['required', 'boolean'],
           'permissions.pendinglist.update-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.update-all-trainers' => ['required', 'boolean'],
           'permissions.pendinglist.update-all-levels' => ['required', 'boolean'],
           'permissions.pendinglist.update-own-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.update-own-trainers' => ['required', 'boolean'],
           'permissions.pendinglist.update-own-levels' => ['required', 'boolean'],
           'permissions.pendinglist.delete-trainees' => ['required', 'boolean'],
           'permissions.pendinglist.delete-own-trainees' => ['required', 'boolean'],
           'permissions.holdlist.assign-trainer' => ['required', 'boolean'],
           'permissions.holdlist.assign-level' => ['required', 'boolean'],
           'permissions.holdlist.view-trainees' => ['required', 'boolean'],
           'permissions.holdlist.view-trainers' => ['required', 'boolean'],
           'permissions.holdlist.view-levels' => ['required', 'boolean'],
           'permissions.holdlist.view-own-trainees' => ['required', 'boolean'],
           'permissions.holdlist.view-own-trainers' => ['required', 'boolean'],
           'permissions.holdlist.view-own-levels' => ['required', 'boolean'],
           'permissions.holdlist.update-trainees' => ['required', 'boolean'],
           'permissions.holdlist.update-all-trainers' => ['required', 'boolean'],
           'permissions.holdlist.update-all-levels' => ['required', 'boolean'],
           'permissions.holdlist.update-own-trainees' => ['required', 'boolean'],
           'permissions.holdlist.update-own-trainers' => ['required', 'boolean'],
           'permissions.holdlist.update-own-levels' => ['required', 'boolean'],
           'permissions.holdlist.delete-trainees' => ['required', 'boolean'],
           'permissions.holdlist.delete-own-trainees' => ['required', 'boolean'],
           'permissions.refundlist.assign-trainer' => ['required', 'boolean'],
           'permissions.refundlist.assign-level' => ['required', 'boolean'],
           'permissions.refundlist.view-trainees' => ['required', 'boolean'],
           'permissions.refundlist.view-trainers' => ['required', 'boolean'],
           'permissions.refundlist.view-levels' => ['required', 'boolean'],
           'permissions.refundlist.view-own-trainees' => ['required', 'boolean'],
           'permissions.refundlist.view-own-trainers' => ['required', 'boolean'],
           'permissions.refundlist.view-own-levels' => ['required', 'boolean'],
           'permissions.refundlist.update-trainees' => ['required', 'boolean'],
           'permissions.refundlist.update-all-trainers' => ['required', 'boolean'],
           'permissions.refundlist.update-all-levels' => ['required', 'boolean'],
           'permissions.refundlist.update-own-trainees' => ['required', 'boolean'],
           'permissions.refundlist.update-own-trainers' => ['required', 'boolean'],
           'permissions.refundlist.update-own-levels' => ['required', 'boolean'],
           'permissions.refundlist.delete-trainees' => ['required', 'boolean'],
           'permissions.refundlist.delete-own-trainees' => ['required', 'boolean'],
           'permissions.blacklist.assign-trainer' => ['required', 'boolean'],
           'permissions.blacklist.assign-level' => ['required', 'boolean'],
           'permissions.blacklist.view-trainees' => ['required', 'boolean'],
           'permissions.blacklist.view-trainers' => ['required', 'boolean'],
           'permissions.blacklist.view-levels' => ['required', 'boolean'],
           'permissions.blacklist.view-own-trainees' => ['required', 'boolean'],
           'permissions.blacklist.view-own-trainers' => ['required', 'boolean'],
           'permissions.blacklist.view-own-levels' => ['required', 'boolean'],
           'permissions.blacklist.update-trainees' => ['required', 'boolean'],
           'permissions.blacklist.update-all-trainers' => ['required', 'boolean'],
           'permissions.blacklist.update-all-levels' => ['required', 'boolean'],
           'permissions.blacklist.update-own-trainees' => ['required', 'boolean'],
           'permissions.blacklist.update-own-trainers' => ['required', 'boolean'],
           'permissions.blacklist.update-own-levels' => ['required', 'boolean'],
           'permissions.blacklist.delete-trainees' => ['required', 'boolean'],
           'permissions.blacklist.delete-own-trainees' => ['required', 'boolean'],
           'permissions.trainees.*' => ['required', 'boolean'],
           'permissions.batches.*' => ['required', 'boolean'],
        ];
    }
}